# Generated by Django 4.2.1 on 2023-05-30 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.RemoveField(
            model_name='task',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='task',
            name='titulo',
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
