# Generated by Django 4.2.1 on 2023-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
